# Website constant 
lang: zh
title: 回忆中的明天
author: MLeo
email: iChochy@qq.com
date_format: "%Y/%m/%d %H:%M:%S"
show_excerpts: false
timezone: Asia/Shanghai
description: 码农小站，写点Java、Swift和感悟，喜欢的小伙伴请关注公众号:iChochy。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ichochy.com" # the base hostname & protocol for your site, e.g. http://example.com


baidu_push: true

rss: RSS
twitter_username: iChochy
github_username:  iChochy
wechat: /assets/img/wx.jpg

# theme: minima

header_pages:
  - index.md
  - blog.md
  - about.md 


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


